name: Build

on:
  push:
    branches-ignore:
      - 'gh-pages'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Ép sử dụng Node 24 để hết bị cảnh báo
      - name: Build # Have to run processing first so the list.json exists to be included in the the deploy
        run: |
          npm ci --prefix processing 
          npm ci --prefix site
          ./build_all_branches.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
